// Auto-generated from studio.html and vibe-to-prompt-dev.html
// All 69 proven prompts for BooManLab

export interface Prompt {
  id: string;
  name: string;
  genre: string;
  vibe: string;
  art: string;
}

export const ALL_PROMPTS: Prompt[] = [
  { id: "P01", name: "The Flute Digger", genre: "italian-film", vibe: `Haunting solo flute, 1960s Italian film score, eerie and cinematic`, art: "/art/P01.jpg" },
  { id: "P02", name: "Cold Organ", genre: "dark-underground", vibe: `Haunting Hammond organ, Eastern European modal jazz, 3am atmosphere`, art: "/art/P02.jpg" },
  { id: "P03", name: "Psych Soul Ghost", genre: "dark-underground", vibe: `Psychedelic soul, harpsichord, ghostly female vocal, hallucinatory`, art: "/art/P03.jpg" },
  { id: "P04", name: "Middle East Menace", genre: "dark-underground", vibe: `Middle Eastern oud, Hijaz scale, cinematic dread, 1970s orchestral`, art: "/art/P04.jpg" },
  { id: "P05", name: "Hybrid Bridge", genre: "boom-bap", vibe: `Rhodes piano in Dorian mode, ghostly vocal hum, lush yet menacing`, art: "/art/P05.jpg" },
  { id: "P06", name: "Black Church", genre: "soul-gospel", vibe: `Hammond B3 organ, gospel choir, small church, raw and spiritual`, art: "/art/P06.jpg" },
  { id: "P07", name: "Late Night Jazz Session", genre: "jazz", vibe: `Small ensemble jazz, walking bass, muted trumpet, intimate late-night`, art: "/art/P07.jpg" },
  { id: "P08", name: "Aching Soul Vocal", genre: "soul-gospel", vibe: `Wailing female soul vocal, gospel-drenched, lush strings, devastating`, art: "/art/P08.jpg" },
  { id: "P09", name: "45 Flip Ready", genre: "chipmunk", vibe: `Upbeat 1960s girl group, bouncy call-and-response, built to speed up`, art: "/art/P09.jpg" },
  { id: "P10", name: "The Break", genre: "drum-break", vibe: `Pure drums, 1970s funk, three-act structure with solo breakdown`, art: "/art/P10.jpg" },
  { id: "P11", name: "Library Cue", genre: "tv-score", vibe: `Production library music, flute or vibraphone, tense and unresolved`, art: "/art/P11.jpg" },
  { id: "P12", name: "Tokyo Deep", genre: "japanese", vibe: `Japanese soul, muffled Rhodes, distant female vocal, dreamy`, art: "/art/P12.jpg" },
  { id: "P13", name: "Cinemascope Nero", genre: "italian-film", vibe: `Italian crime film, wah-wah guitar, walking bass, flute and strings`, art: "/art/P13.jpg" },
  { id: "P14", name: "Midnight Sanctuary", genre: "soulful-house", vibe: `Underground soulful house, gospel piano, powerful female vocal`, art: "/art/P14.jpg" },
  { id: "P15", name: "Filtered Gold", genre: "disco-house", vibe: `French disco house, filter sweep bass, disco strings, euphoric`, art: "/art/P15.jpg" },
  { id: "P16", name: "Barrio Nocturno", genre: "latin", vibe: `Latin soul orchestra, dark strings, congas, ghostly vocal, midnight`, art: "/art/P16.jpg" },
  { id: "P17", name: "Giallo Nero", genre: "italian-film", vibe: `Italian horror score, pulsing bass, analog synth arpeggio, funeral pace`, art: "/art/P17.jpg" },
  { id: "P18", name: "Murda Muzik Source", genre: "cinematic-dark", vibe: `Dark orchestral, obsessive minor piano motif, mournful strings, menace`, art: "/art/P18.jpg" },
  { id: "P19", name: "Late Night Broadcast", genre: "tv-score", vibe: `TV crime drama cue, electric piano, wah-wah guitar, surveillance 2am`, art: "/art/P19.jpg" },
  { id: "P20", name: "S\u00e3o Paulo Basement", genre: "brazilian", vibe: `Brazilian jazz-funk, Rhodes piano, breathy flute, humid room`, art: "/art/P20.jpg" },
  { id: "P21", name: "Thunder Soul", genre: "boom-bap", vibe: `Live high school funk band, raw and imperfect, flute solo, gymnasium`, art: "/art/P21.jpg" },
  { id: "P22", name: "Stadium Brass", genre: "marching-band", vibe: `College marching band, 60-80 horns, solo trumpet, triumphant`, art: "/art/P22.jpg" },
  { id: "P23", name: "Dark Cinematic Loop", genre: "cinematic-dark", vibe: `Minimal piano, slow string pads, deep cello, cinematic grief`, art: "/art/P23.jpg" },
  { id: "P24", name: "Warsaw Glass", genre: "polish-jazz", vibe: `Cold Polish jazz, crystalline piano, Harmon-muted trumpet, midnight`, art: "/art/P24.jpg" },
  { id: "P25", name: "Dead Sea Scroll", genre: "israeli-psych", vibe: `Israeli psych folk, oud in Hijaz, bouzouki tremolo, ancient`, art: "/art/P25.jpg" },
  { id: "P26", name: "Budapest Hammer", genre: "hungarian-psych", vibe: `Hungarian psych folk, cimbalom and t\\u00e1rogat\\u00f3, fuzz drones, intense`, art: "/art/P26.jpg" },
  { id: "P27", name: "Autobahn Noir", genre: "krautrock", vibe: `German kosmische, Moog filter sweeps, Farfisa drone, cold and vast`, art: "/art/P27.jpg" },
  { id: "P28", name: "Anatolian Dust", genre: "turkish-psych", vibe: `Turkish psych, amplified ba\\u011flama in Hicaz makam, raw and furious`, art: "/art/P28.jpg" },
  { id: "P29", name: "Addis Midnight", genre: "ethio-jazz", vibe: `Ethio-Jazz, Hammond organ in ambassel mode, raw tenor sax, 1973`, art: "/art/P29.jpg" },
  { id: "P30", name: "Accra Gold", genre: "ghana-funk", vibe: `Ghanaian highlife funk, shimmering guitar ostinato, cowbell, bright`, art: "/art/P30.jpg" },
  { id: "P31", name: "Bombay Reel", genre: "bollywood", vibe: `Bollywood film score, solo sitar, tablas, lush strings, Bombay 1970s`, art: "/art/P31.jpg" },
  { id: "P32", name: "Paris Noir", genre: "french-library", vibe: `French library music, harpsichord, solo flute, Parisian orchestral noir`, art: "/art/P32.jpg" },
  { id: "P33", name: "Sigma Gold", genre: "philly-soul", vibe: `Philly soul orchestral, massive string section, flugelhorn solo, dramatic`, art: "/art/P33.jpg" },
  { id: "P34", name: "Shaft Alley", genre: "blaxploitation", vibe: `Blaxploitation score, wah-wah guitar, muted trumpet, urban midnight 1973`, art: "/art/P34.jpg" },
  { id: "P35", name: "Astral Temple", genre: "spiritual-jazz", vibe: `Spiritual jazz, Rhodes drone, solo flute, congas, cosmic and devotional`, art: "/art/P35.jpg" },
  { id: "P36", name: "Chrome Love", genre: "synth-funk", vibe: `1980s synth-funk, Prophet pads, Moog bass, talk box, quiet storm`, art: "/art/P36.jpg" },
  { id: "P37", name: "Temple Fist", genre: "kung-fu-score", vibe: `Shaw Brothers film score, erhu, Chinese percussion, martial arts tension`, art: "/art/P37.jpg" },
  { id: "P38", name: "Aegean Ghost", genre: "greek-rebetiko", vibe: `Greek laiko, bouzouki tremolo, Phrygian mode, Athens nightclub 1972`, art: "/art/P38.jpg" },
  { id: "P39", name: "Shadow Temple", genre: "8-bit", vibe: `Slow eerie 8-bit dungeon theme, Phrygian pulse wave, digital silence, 1987 RPG cartridge`, art: "/art/P39.jpg" },
  { id: "P40", name: "Tiny Ghost", genre: "childrens-toy", vibe: `Budget 1970s children\\u2019s record, toy piano, glockenspiel, music box, haunting when pitched down`, art: "/art/P40.jpg" },
  { id: "P41", name: "Lusaka Fuzz", genre: "zamrock", vibe: `Zambian psych rock, ragged fuzz guitar, indigenous folk intervals, Copperbelt 1975`, art: "/art/P41.jpg" },
  { id: "P42", name: "Kinshasa Gold", genre: "congolese-rumba", vibe: `Congolese rumba, cascading fingerpicked guitar sebene, bright and liquid`, art: "/art/P42.jpg" },
  { id: "P43", name: "Medell\u00edn Fuzz", genre: "colombian-cumbia", vibe: `Colombian psychedelic cumbia, fuzz guitar, gaita melodies, Farfisa organ`, art: "/art/P43.jpg" },
  { id: "P44", name: "Lima Tremolo", genre: "peruvian-chicha", vibe: `Peruvian chicha, spring-reverb tremolo guitar, Andean pentatonic, lo-fi Lima`, art: "/art/P44.jpg" },
  { id: "P45", name: "Bangkok Ghost", genre: "thai-psych", vibe: `Thai luk thung psych, fuzz guitar, hammered dulcimer, ornamental melodies`, art: "/art/P45.jpg" },
  { id: "P46", name: "Phnom Penh Sunrise", genre: "cambodian-rock", vibe: `Cambodian rock, surf tremolo guitar, Khmer pentatonic, devastatingly rare`, art: "/art/P46.jpg" },
  { id: "P47", name: "Moscow Midnight", genre: "soviet-estrada", vibe: `Soviet jazz-funk, conservatory precision, forbidden funk, Melodiya pressing`, art: "/art/P47.jpg" },
  { id: "P48", name: "Belgrade Brass", genre: "yugoslav-funk", vibe: `Yugoslav prog-funk, Rhodes in 7/8 time, Balkan Phrygian, Romani harmony`, art: "/art/P48.jpg" },
  { id: "P49", name: "Seoul Banned", genre: "korean-psych", vibe: `Korean psych rock, fuzz guitar, gayageum zither, banned and destroyed pressings`, art: "/art/P49.jpg" },
  { id: "P50", name: "Tokyo Underground", genre: "japanese-jazz-funk", vibe: `Japanese jazz-funk, pristine Rhodes, tenor sax, audiophile Tokyo pressing`, art: "/art/P50.jpg" },
  { id: "P51", name: "Oran Cassette", genre: "algerian-rai", vibe: `Algerian ra\\u00ef, gasba bamboo flute, Hijaz scale, cassette-only distribution`, art: "/art/P51.jpg" },
  { id: "P52", name: "Marrakech Trance", genre: "moroccan-gnawa", vibe: `Moroccan Gnawa trance, sintir bass lute, krakeb iron castanets, ceremonial`, art: "/art/P52.jpg" },
  { id: "P53", name: "Port-au-Prince Ceremony", genre: "haitian-vodou", vibe: `Haitian vodou-jazz, tanbou drums, accordion, vaksin bamboo trumpet`, art: "/art/P53.jpg" },
  { id: "P54", name: "Tehran Ghost", genre: "iranian-psych", vibe: `Iranian pre-revolution psych, santur, kamancheh, quarter-tone melodies, destroyed pressings`, art: "/art/P54.jpg" },
  { id: "P55", name: "Kabul Rubab", genre: "afghan-folk", vibe: `Afghan folk-pop, rubab with 15 sympathetic strings, harmonium, Radio Afghanistan`, art: "/art/P55.jpg" },
  { id: "P56", name: "Soweto Whistle", genre: "south-african-jazz", vibe: `South African township jazz, penny whistle, marabi piano vamp, mbaqanga bass`, art: "/art/P56.jpg" },
  { id: "P57", name: "Havana Descarga", genre: "afro-cuban", vibe: `Afro-Cuban descarga, piano montuno, tres guitar, charanga flute, clave-locked`, art: "/art/P57.jpg" },
  { id: "P58", name: "Sunset Strip", genre: "g-funk", vibe: `Mid 1970s Ohio/Detroit P-Funk, high Moog melody, deep bass, clavinet, horn stabs, raw funk`, art: "/art/P58.jpg" },
  { id: "P59", name: "Detroit Mothership", genre: "p-funk", vibe: `1975 Detroit funk, Moog bass, clavinet through Mutron, tight horn stabs, one-chord vamp`, art: "/art/P59.jpg" },
  { id: "P60", name: "Dungeon Smoke", genre: "atl-dungeon", vibe: `Early 1970s Southern psychedelic soul, wah guitar, Hammond B3, flute, church meets acid`, art: "/art/P60.jpg" },
  { id: "P61", name: "Gulf Coast Player", genre: "houston-funk", vibe: `Early 1970s cinematic soul soundtrack, lush strings, wah guitar, flugelhorn, blaxploitation`, art: "/art/P61.jpg" },
  { id: "P62", name: "Memphis Cassette", genre: "memphis-dark", vibe: `Mid 1970s European horror score, cold synth ostinato, pipe organ tritone, celesta, dread`, art: "/art/P62.jpg" },
  { id: "P63", name: "Second Line Ghost", genre: "nola-bounce", vibe: `Early 1970s New Orleans brass band field recording, sousaphone, parade trumpet, second line`, art: "/art/P63.jpg" },
  { id: "P64", name: "Dark Crystal", genre: "melodic-trap-source", vibe: `Dark melodic source material, plucked synth, music box bell, sparse piano, vault loop`, art: "/art/P64.jpg" },
  { id: "P65", name: "Phrygian Blade", genre: "drill-source", vibe: `Dark aggressive source, Phrygian string stabs, cello drone, distorted synth, hostile tension`, art: "/art/P65.jpg" },
  { id: "VC01", name: "Soul Confession", genre: "vocal-chop", vibe: `Philly soul, wailing female vocal, lush strings and Rhodes, devastating and choppable`, art: "/art/VC01.jpg" },
  { id: "VC02", name: "Church Window", genre: "vocal-chop", vibe: `Black church gospel, solo female voice over Hammond B3, choir call and response`, art: "/art/VC02.jpg" },
  { id: "VC03", name: "Midnight Plea", genre: "vocal-chop", vibe: `Detroit soul, male falsetto over Rhodes and strings, fragile and devastating`, art: "/art/VC03.jpg" },
  { id: "VC04", name: "Golden Dust", genre: "vocal-chop", vibe: `Girl group trio, bright harmonies, punchy horns, built to be pitched up and chipmunked`, art: "/art/VC04.jpg" },
];

export const ALL_GENRES = [...new Set(ALL_PROMPTS.map(p => p.genre))];
